version: '3.4'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    command: "postgres -c log_destination='stderr' -c log_statement=all -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h ' -c log_checkpoints=on -c log_connections=on -c log_lock_waits=on -c log_temp_files=0 -c log_autovacuum_min_duration=0 -c log_error_verbosity=default -c lc_messages='C' -c log_min_duration_statement=0"
    volumes:
      - morango-postgres:/var/lib/postgresql/data
volumes:
  morango-postgres:
